title: RE:FORM Telegram App
description: Приложение для обмена фидбеком между дизайнерами
baseurl: ''
url: 'https://ваш-юзернейм.github.io'
github_username: ваш-юзернейм

# Настройки для GitHub Pages
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Отключить обработку
include: ['.htaccess']
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules

# Headers для корректной работы в iframe
header_files:
  - '_headers'
