title: RE:FORM Telegram App
description: Приложение для обмена фидбеком между дизайнерами
baseurl: ''
url: 'https://ваш-юзернейм.github.io'
github_username: ваш-юзернейм

theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-seo-tag

include: ['.htaccess']
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules

header_files:
  - '_headers'
